Repository alshedivat/al-folio, pull requests merged in 2023-10, with the labels that each got.

#1789 Update README.md
  README.md
Labels: ignore-for-release

#1796 Remove by year grouping from selected publications
  _includes/selected_papers.html
Labels: bug-fix

#1797 Make publication thumbnails optional + fix small layout bugs
  _config.yml
  _includes/scripts/badges.html
  _layouts/bib.html
Labels: enhancement

#1804 fix reference disappearing for distill blog in absence of author
  _layouts/distill.html
  assets/js/distillpub/template.v2.js
Labels: bug-fix
